Fix/bytes event
pnetwork-association/pnetwork-v4 pull request #44
Opened 2024-10-21 16:59 UTC by envin3

2024-10-25 15:24 UTC, gitmp01 requested changes

2024-10-25 15:24 UTC, gitmp01 commented on solidity/test/hardhat/forked-environment/ptoken-upgrade.test.js
> +          data: decodedEvent.data,
cleaner for the reader eyes:
```suggestion
          ...decodedEvent,
          nonce: swapEvent.topics[1],
```

2024-10-25 23:42 UTC, envin3 commented on solidity/test/forge/Integration.t.sol
> +        }
debug code forgot there

2024-10-28 08:13 UTC, gitmp01 approved these changes
LGTM

2024-10-28 08:13 UTC, gitmp01 commented on solidity/test/forge/Helper.sol
> +    }
:+1:

2024-10-28 08:31 UTC, merged