Add pam specific tests
pnetwork-association/pnetwork-v4 pull request #48
Opened 2024-10-30 07:55 UTC by gitmp01

2024-11-04 08:24 UTC, gitmp01 commented on cpp/contracts/adapter.cpp
> +      asset quantity(operation.amount.amount, search_token_bytes->xerc20_symbol);
See `operation.hpp`

2024-11-04 08:24 UTC, gitmp01 commented on cpp/test/adapter-local.test.js
Sorry about this diff, but I have vscode auto-formatting enabled and is annoying

2024-11-05 01:13 UTC, envin3 commented on cpp/contracts/adapter.cpp
> +void adapter::setorigin(bytes chain_id, bytes emitter, bytes topic_zero) {
nice

2024-11-05 01:15 UTC, envin3 commented on cpp/contracts/pam.hpp
> +        void check_authorization(name adapter, const operation& operation, const metadata& metadata, checksum256& event_id) {
this function isn't updated. We need a merge.

2024-11-05 01:16 UTC, envin3 commented on cpp/contracts/test.pam.cpp
> +void testpam::isauthorized(const operation& operation,const metadata& metadata) {
:+1:

2024-11-05 01:19 UTC, envin3 requested changes
we need a merge with https://github.com/pnetwork-association/pnetwork-v4/pull/51

2024-11-06 20:57 UTC, merged