feat(adapter): add cooldown period for tee set up
pnetwork-association/pnetwork-v4 pull request #65
Opened 2024-11-08 22:20 UTC by envin3

Cooldown period for new tee set

2024-11-09 09:34 UTC, gitmp01 requested changes
Looks good overall, could you add a test showing the rejection when someone tries to update the pubkey before the grace period? You can control time in tests through:
```js
const { TimePointSec } = require('@wharfkit/antelope')
const timestamp = TimePointSec.fromMilliseconds(Date.now())

blockchain.setTime(timestamp)
```

2024-11-09 09:34 UTC, gitmp01 commented on cpp/contracts/pam.hpp
> +        static constexpr uint64_t TEE_ADDRESS_CHANGE_GRACE_PERIOD = 172800;
```suggestion
        static constexpr uint64_t TEE_ADDRESS_CHANGE_GRACE_PERIOD = 172800; // 48 hours
```

2024-11-10 11:15 UTC, gitmp01 approved these changes

2024-11-10 11:15 UTC, merged

2024-11-10 15:36 UTC, envin3 commented on cpp/test/adapter.test.js
> +      blockchain.setTime(timestamp)
nice

2024-11-10 15:37 UTC, envin3 reviewed
LGTM